# Generated by Django 3.0.8 on 2020-07-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('selesai', models.BooleanField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Client')),
                ('kategori_penanganan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.KategoriPenanganan')),
                ('kategori_pengaduan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.KategoriPengaduan')),
            ],
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respon', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('oleh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pengaduan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pelayanan.Pengaduan')),
            ],
        ),
    ]
