# Generated by Django 3.0.8 on 2020-07-17 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pelayanan', '0002_auto_20200716_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='oleh',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='respon',
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respon', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('oleh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pengaduan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pelayanan.Pengaduan')),
            ],
        ),
    ]
