# Generated by Django 3.0.8 on 2020-07-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pelayanan', '0003_auto_20200717_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='oleh',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='respon',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Respon',
        ),
    ]
