# Generated by Django 3.0.8 on 2020-07-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan', '0007_auto_20200717_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduans',
            name='respon',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
