# Generated by Django 3.0.8 on 2020-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instansi',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
