# Generated by Django 3.0.8 on 2020-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_instansi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='instansi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
