# Generated by Django 3.0.8 on 2020-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoripengaduan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
